# frozen_string_literal: true

source 'https://rubygems.org'

gem 'lograge', '~> 0.14.0'
gem 'logstash-event', '~> 1.2.02'
gem 'opentelemetry-exporter-otlp', '~> 0.29.1'
gem 'opentelemetry-instrumentation-all', '~> 0.72.0'
gem 'opentelemetry-sdk', '~> 1.6.0'
